#! /usr/bin/env python3
# -*- coding: utf-8 -*-
# Filename:    generate_catalog_snapshot.py
# Description: Convert the indigo-device-catalog by-class/*.json files into a
#              vendored Python snapshot module (catalog_snapshot.py) inside the
#              Claude Bridge bundle. Vendoring as a .py dict-literal — not a
#              bundled .json read at runtime — sidesteps the Indigo
#              `__file__`-undefined trap and needs no runtime file I/O.
#
#              Reads the by-class/*.json files, NOT the merged catalog.json:
#              the by-class files carry the DENSE capability map (explicit
#              True AND False per flag), which is what drives capability
#              refusals; the merged catalog.json is a lossy only-true view for
#              the Dashboards renderer. The catalogue is CliveS's own
#              (Highsteads indigo-device-catalog, generated from the live
#              estate), so Claude Bridge's capability-awareness runs entirely
#              on our own data with no external dependency.
#
#              Usage:
#                python3 scripts/generate_catalog_snapshot.py \
#                    --catalog-dir ~/Documents/GitHub/indigo-device-catalog/catalog \
#                    --out "<bundle>/mcp_server/common/device_catalog/catalog_snapshot.py"
# Author:      CliveS & Claude Opus 4.8
# Date:        23-07-2026
# Version:     2.0

import argparse
import glob
import json
import os
import pprint

_DEFAULT_CATALOG_DIR = os.path.expanduser(
    "~/Documents/GitHub/indigo-device-catalog/catalog")

_HEADER = '''\
"""Vendored snapshot of the Highsteads indigo-device-catalog (dense).

AUTO-GENERATED by scripts/generate_catalog_snapshot.py — do not edit by
hand; regenerate from a catalog checkout instead. Plain dicts, no runtime
I/O, no network (same vendoring pattern as the plugin's other bundled
data).

PROFILES maps (pluginId, deviceTypeId) -> a profile dict carrying the
DENSE capability flag map (explicit True AND False per flag, which is
what lets capability refusals fire safely) plus base-class / model /
display-state metadata. `device_catalog.profile_for` is the lookup
helper. The catalogue is CliveS's own, generated from the live estate;
capability-awareness in Claude Bridge runs on this data with no external
dependency.
"""

# The generator writes SNAPSHOT_META and PROFILES below.
'''


def load_profiles(catalog_dir: str) -> dict:
    """Flatten every by-class/*.json profile into
    {(pluginId, deviceTypeId): profile} with the dense capability map."""
    profiles = {}
    by_class = os.path.join(catalog_dir, "by-class")
    files = sorted(glob.glob(os.path.join(by_class, "*.json")))
    if not files:
        raise SystemExit(
            f"no by-class/*.json under {by_class} — pass --catalog-dir a "
            f"catalogue checkout, or regenerate the catalogue first")
    for path in files:
        with open(path, encoding="utf-8") as fh:
            doc = json.load(fh)
        base_class = doc.get("baseClass", "")
        for prof in doc.get("profiles", []):
            plugin_id = prof.get("pluginId")
            type_id = prof.get("deviceTypeId")
            if not plugin_id or not type_id:
                continue
            entry = {
                "base_class": base_class,
                "capabilities": dict(prof.get("capabilities") or {}),
            }
            if prof.get("model"):
                entry["model"] = prof["model"]
            if prof.get("displayStateId"):
                entry["display_state_id"] = prof["displayStateId"]
            if prof.get("states"):
                entry["states"] = sorted(prof["states"].keys())
            profiles[(plugin_id, type_id)] = entry
    return profiles


def main() -> int:
    ap = argparse.ArgumentParser(description="Vendor a dense device-catalogue snapshot")
    ap.add_argument("--catalog-dir", default=_DEFAULT_CATALOG_DIR,
                    help="path to the indigo-device-catalog catalog/ dir")
    ap.add_argument("--out", required=True, help="path to write catalog_snapshot.py")
    args = ap.parse_args()

    profiles = load_profiles(args.catalog_dir)
    # Provenance from the catalogue's own _index.json when present.
    meta = {"profile_count": len(profiles)}
    index_path = os.path.join(args.catalog_dir, "_index.json")
    if os.path.isfile(index_path):
        with open(index_path, encoding="utf-8") as fh:
            idx = json.load(fh)
        for key in ("generated", "indigoVersion"):
            if idx.get(key):
                meta[key] = idx[key]

    ordered = {key: profiles[key] for key in sorted(profiles)}
    body = [
        _HEADER,
        "SNAPSHOT_META = " + pprint.pformat(meta, width=100, sort_dicts=True),
        "",
        "PROFILES = " + pprint.pformat(ordered, width=100, sort_dicts=True),
        "",
    ]
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(body))

    dense = sum(1 for p in profiles.values()
                if any(v is False for v in p["capabilities"].values()))
    print(f"Wrote {len(profiles)} profiles to {args.out} "
          f"({dense} carry at least one explicit False flag)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
