#! /usr/bin/env python
# -*- coding: utf-8 -*-
# Filename:    generate_tool_doc.py
# Description: Generate the MCP tool reference (docs/tools.md) from the tool
#              registry, and keep every tool count written in prose in the
#              README and the documentation site in step with it.
# Author:      CliveS & Claude Opus 4.8; Claude Fable 5.1 (1.1); Claude Opus 5.5 (2.0)
# Date:        08-06-2026 (1.1: 11-09-2026, 2.0: 23-09-2026)
# Version:     2.0
#
# v2.0 (23-09-2026): reads the registry itself (mcp_server/registry.py) instead
#   of AST-parsing mcp_handler.py and scope_manager.py, which no longer hold the
#   tools. A stub `indigo` module is installed first, exactly as tests/conftest.py
#   does, so it still runs on a plain runner with no Indigo. It now also owns
#   every prose tool count — README.md, docs/*.md and the site description in
#   docs/_config.yml — and --check fails on any that is stale. Until now it kept
#   the table and the headline current and nothing else, so the README said 159
#   while _config.yml said 168.
# v1.1 (11-09-2026): the table moved out of the README into docs/tools.md.
#
# Usage:
#   python3 scripts/generate_tool_doc.py            # print the table to stdout
#   python3 scripts/generate_tool_doc.py --write    # update docs/tools.md and every count
#   python3 scripts/generate_tool_doc.py --check    # exit 1 if anything is stale
#
# The table is written between these markers in docs/tools.md:
#   <!-- BEGIN TOOL TABLE -->
#   <!-- END TOOL TABLE -->

import argparse
import glob
import os
import re
import sys
import types
from unittest.mock import MagicMock

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUNDLE_SP = os.path.join(REPO_ROOT, "Claude Bridge.indigoPlugin", "Contents", "Server Plugin")
DOC_PATH = os.path.join(REPO_ROOT, "docs", "tools.md")
README_PATH = os.path.join(REPO_ROOT, "README.md")
CONFIG_PATH = os.path.join(REPO_ROOT, "docs", "_config.yml")

BEGIN_MARKER = "<!-- BEGIN TOOL TABLE -->"
END_MARKER = "<!-- END TOOL TABLE -->"

# Display order + heading for each scope tier.
SCOPE_ORDER = [
    ("read", "Read tools", "Pure queries — no state change. Require the `read` scope."),
    ("write", "Write tools", "Modify Indigo state. Require `write` (or `admin`)."),
    (
        "admin",
        "Admin tools",
        "Destructive / irreversible / code-execution / lifecycle / physical-security / data leaving the house. Require `admin`.",
    ),
]


def _read(path):
    # Indigo's embedded Python defaults open() to ASCII; be explicit (UTF-8 source).
    with open(path, encoding="utf-8") as f:
        return f.read()


def _install_indigo_stub() -> None:
    """The same stub tests/conftest.py installs: enough for the plugin's modules
    to import on a machine with no Indigo."""
    if "indigo" in sys.modules:
        return
    ind = types.ModuleType("indigo")

    class _PluginBase:
        def __init__(self, *a, **k):
            pass

    ind.PluginBase = _PluginBase
    ind.Dict = dict
    ind.List = list
    for attr in ("server", "devices", "variables", "kStateImageSel", "activePlugin",
                 "kDeviceAction", "Variable", "Device", "kHvacMode", "kFanMode",
                 "thermostat", "dimmer", "device", "actionGroups", "triggers", "schedules"):
        setattr(ind, attr, MagicMock())
    sys.modules["indigo"] = ind


def load_registry(bundle_sp: str = BUNDLE_SP):
    """Import the tool registry from a bundle and return {name: ToolSpec}."""
    _install_indigo_stub()
    if bundle_sp not in sys.path:
        sys.path.insert(0, bundle_sp)
    from mcp_server import registry
    return registry.load()


def count_by_scope(reg):
    counts = {"read": 0, "write": 0, "admin": 0}
    for spec in reg.values():
        counts[spec.scope] += 1
    return counts


def build_table(reg):
    """Return the markdown table, one section per scope."""
    buckets = {"read": [], "write": [], "admin": []}
    for name in sorted(reg):
        buckets[reg[name].scope].append(name)

    lines = [
        f"<!-- AUTO-GENERATED by scripts/generate_tool_doc.py — {len(reg)} tools. Do not edit by hand. -->",
        "",
    ]
    for scope, heading, blurb in SCOPE_ORDER:
        names = buckets[scope]
        if not names:
            continue
        lines.append(f"### {heading} ({len(names)})")
        lines.append("")
        lines.append(f"_{blurb}_")
        lines.append("")
        lines.append("| Tool | Description |")
        lines.append("|------|-------------|")
        for name in names:
            desc = reg[name].description.replace("\n", " ").replace("|", "\\|").strip()
            lines.append(f"| `{name}` | {desc} |")
        lines.append("")
    # The trailing BLANK line matters: the END marker follows the table, and
    # kramdown (GitHub Pages) refuses to parse a table whose block also holds a
    # line with no pipe in it (measured 11-09-2026).
    return "\n".join(lines).rstrip() + "\n\n"


def inject_table(page, table_md):
    if BEGIN_MARKER not in page or END_MARKER not in page:
        raise SystemExit(
            f"docs/tools.md is missing the markers.\nAdd these two lines where the "
            f"table should go:\n  {BEGIN_MARKER}\n  {END_MARKER}"
        )
    pre = page.split(BEGIN_MARKER)[0]
    post = page.split(END_MARKER)[1]
    return f"{pre}{BEGIN_MARKER}\n{table_md}{END_MARKER}{post}"


# ── Prose counts ─────────────────────────────────────────────────────────────
#
# Every place a count of built-in tools is written in prose. A number is only
# rewritten where the words around it say it is THE tool count, so an unrelated
# number is never touched. History is never rewritten: docs/changelog.md is
# skipped, and so is the README's "What's new" (a verbatim copy of the newest
# changelog entries, pinned to it by tests/test_docs_site.py).

_TOTAL_PATTERNS = [
    re.compile(r"(\*\*)(\d+)( tools(?:, grouped by security scope\.)?\*\*)", re.I),
    re.compile(r"(\*\*)(\d+)( MCP tools\*\*)", re.I),
    re.compile(r"(\bThe )(\d+)( tools by what)", re.I),
    re.compile(r"(\bsee )(\d+)( `indigo-mcp` tools)", re.I),
    re.compile(r"(\bshould see )(\d+)( tools)", re.I),
    re.compile(r"(\bthrough )(\d+)( tools\.)", re.I),
    re.compile(r"(\bon top of the )(\d+)( below)", re.I),
    re.compile(r"(\()(\d+)( tools\))", re.I),
    re.compile(r"(— )(\d+)( tools\. Do not edit)", re.I),
]
_SCOPE_PATTERNS = {
    scope: re.compile(r"(\*\*)(\d+)( " + scope + r"\*\*)") for scope in ("read", "write", "admin")
}
# An ASCII diagram cell like "│  (159 tools) │" must keep its width when the
# number changes length, or the box's right edge moves.
_DIAGRAM = re.compile(r"\((\d+) tools\)( *)(│)")


def _protected_spans(path, text):
    """Character ranges the count rewrite must leave alone."""
    spans = []
    if os.path.basename(path) == "README.md":
        m = re.search(r"^## What's new\s*$", text, re.M)
        if m:
            end = re.search(r"^## ", text[m.end():], re.M)
            spans.append((m.start(), m.end() + end.start() if end else len(text)))
    return spans


def _sub_outside(pattern, repl, text, spans):
    def _fn(m):
        if any(a <= m.start() < b for a, b in spans):
            return m.group(0)
        return repl(m)
    return pattern.sub(_fn, text)


def rewrite_counts(path, text, total, by_scope):
    spans = _protected_spans(path, text)

    def _diagram(m):
        new = f"({total} tools)"
        pad = len(m.group(0)) - len(m.group(3)) - len(new)
        return new + " " * max(pad, 1) + m.group(3)

    text = _sub_outside(_DIAGRAM, _diagram, text, spans)
    spans = _protected_spans(path, text)
    for pattern in _TOTAL_PATTERNS:
        text = _sub_outside(pattern, lambda m: f"{m.group(1)}{total}{m.group(3)}", text, spans)
        spans = _protected_spans(path, text)
    for scope, pattern in _SCOPE_PATTERNS.items():
        text = _sub_outside(pattern, lambda m, s=scope: f"{m.group(1)}{by_scope[s]}{m.group(3)}",
                            text, spans)
        spans = _protected_spans(path, text)
    return text


# A safety net for phrasings the patterns above do not know: any number
# written within three words of "tools" that is not the current count.
_ANY_COUNT = re.compile(r"\b(\d{2,3})((?:\s+[`*\w-]+){0,3}?)\s+tools\b")


def stray_counts(path, text, total, by_scope):
    """Tool counts in `text` that disagree with the registry and that
    rewrite_counts has no pattern for. Reported, never guessed at."""
    spans = _protected_spans(path, text)
    found = []
    for m in _ANY_COUNT.finditer(text):
        if any(a <= m.start() < b for a, b in spans):
            continue
        scope = next((sc for sc in by_scope if sc in m.group(2)), None)
        expected = by_scope[scope] if scope else total
        if int(m.group(1)) != expected:
            line = text.count("\n", 0, m.start()) + 1
            found.append(f"{os.path.relpath(path, REPO_ROOT)}:{line}: '{m.group(0)}'")
    return found


def count_files():
    files = [README_PATH, CONFIG_PATH]
    for path in sorted(glob.glob(os.path.join(REPO_ROOT, "docs", "*.md"))):
        if os.path.basename(path) != "changelog.md":
            files.append(path)
    return files


def render_all(reg):
    """{path: (current text, text as it should be)} for every owned file."""
    total = len(reg)
    by_scope = count_by_scope(reg)
    table = build_table(reg)
    out = {}
    for path in count_files():
        current = _read(path)
        wanted = rewrite_counts(path, current, total, by_scope)
        if path == DOC_PATH:
            wanted = inject_table(wanted, table)
        out[path] = (current, wanted)
    return out


def main():
    ap = argparse.ArgumentParser(description="Generate the MCP tool reference and tool counts.")
    ap.add_argument("--write", action="store_true", help="update docs/tools.md and every count")
    ap.add_argument("--check", action="store_true", help="exit 1 if anything is stale")
    args = ap.parse_args()

    reg = load_registry()
    rendered = render_all(reg)

    strays = [s for p, (_cur, want) in rendered.items()
              for s in stray_counts(p, want, len(reg), count_by_scope(reg))]
    for stray in strays:
        print(f"FAIL: a tool count the generator cannot rewrite — reword it or teach "
              f"rewrite_counts the phrase: {stray}", file=sys.stderr)

    if args.check:
        stale = [os.path.relpath(p, REPO_ROOT) for p, (cur, want) in rendered.items() if cur != want]
        if stale:
            print("FAIL: stale tool reference or tool count in: " + ", ".join(stale)
                  + " — run `python3 scripts/generate_tool_doc.py --write`.", file=sys.stderr)
        sys.exit(1 if (stale or strays) else 0)

    if args.write:
        changed = []
        for path, (cur, want) in rendered.items():
            if cur != want:
                with open(path, "w", encoding="utf-8") as f:
                    f.write(want)
                changed.append(os.path.relpath(path, REPO_ROOT))
        print(f"{len(reg)} tools {count_by_scope(reg)}; updated: {', '.join(changed) or 'nothing'}")
        if strays:
            sys.exit(1)
    else:
        print(build_table(reg))


if __name__ == "__main__":
    main()
